# Download Gradle wrapper files

$ErrorActionPreference = "Stop"

Write-Host "=== Downloading Gradle Wrapper ===" -ForegroundColor Cyan

$gradleVersion = "8.5"
$baseUrl = "https://raw.githubusercontent.com/gradle/gradle/v$gradleVersion/gradle/wrapper"

# Create directories
New-Item -ItemType Directory -Path "gradle\wrapper" -Force | Out-Null

# Download gradle-wrapper.jar
Write-Host "Downloading gradle-wrapper.jar..." -ForegroundColor Yellow
try {
    $jarUrl = "https://github.com/gradle/gradle/raw/v$gradleVersion/gradle/wrapper/gradle-wrapper.jar"
    Invoke-WebRequest -Uri $jarUrl -OutFile "gradle\wrapper\gradle-wrapper.jar" -UseBasicParsing
    Write-Host "  ✓ Downloaded gradle-wrapper.jar" -ForegroundColor Green
} catch {
    Write-Host "  ✗ Failed to download. Trying alternative method..." -ForegroundColor Yellow
    # Alternative: use direct download
    $altUrl = "https://services.gradle.org/distributions/gradle-wrapper.jar"
    try {
        Invoke-WebRequest -Uri $altUrl -OutFile "gradle\wrapper\gradle-wrapper.jar" -UseBasicParsing
        Write-Host "  ✓ Downloaded gradle-wrapper.jar (alternative)" -ForegroundColor Green
    } catch {
        Write-Host "  ✗ Could not download wrapper JAR" -ForegroundColor Red
        Write-Host "  Please download manually from: https://gradle.org/releases/" -ForegroundColor Yellow
        exit 1
    }
}

# Create gradle-wrapper.properties
Write-Host "Creating gradle-wrapper.properties..." -ForegroundColor Yellow
$wrapperProps = @"
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-$gradleVersion-bin.zip
networkTimeout=10000
validateDistributionUrl=true
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
"@
Set-Content -Path "gradle\wrapper\gradle-wrapper.properties" -Value $wrapperProps
Write-Host "  ✓ Created gradle-wrapper.properties" -ForegroundColor Green

# Create gradlew.bat
Write-Host "Creating gradlew.bat..." -ForegroundColor Yellow
$gradlewBat = @'
@if "%DEBUG%"=="" @echo off
@rem Gradle startup script for Windows

@rem Set local scope for the variables with windows NT shell
if "%OS%"=="Windows_NT" setlocal

set DIRNAME=%~dp0
if "%DIRNAME%"=="" set DIRNAME=.
set APP_BASE_NAME=%~n0
set APP_HOME=%DIRNAME%

@rem Resolve any "." and ".." in APP_HOME to make it shorter.
for %%i in ("%APP_HOME%") do set APP_HOME=%%~fi

@rem Add default JVM options here.
set DEFAULT_JVM_OPTS="-Xmx64m" "-Xms64m"

@rem Find java.exe
if defined JAVA_HOME goto findJavaFromJavaHome

set JAVA_EXE=java.exe
%JAVA_EXE% -version >NUL 2>&1
if %ERRORLEVEL% equ 0 goto execute

echo.
echo ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.
echo.
echo Please set the JAVA_HOME variable in your environment to match the
echo location of your Java installation.

goto fail

:findJavaFromJavaHome
set JAVA_HOME=%JAVA_HOME:"=%
set JAVA_EXE=%JAVA_HOME%/bin/java.exe

if exist "%JAVA_EXE%" goto execute

echo.
echo ERROR: JAVA_HOME is set to an invalid directory: %JAVA_HOME%
echo.
echo Please set the JAVA_HOME variable in your environment to match the
echo location of your Java installation.

goto fail

:execute
@rem Setup the command line
set CLASSPATH=%APP_HOME%\gradle\wrapper\gradle-wrapper.jar

@rem Execute Gradle
"%JAVA_EXE%" %DEFAULT_JVM_OPTS% %JAVA_OPTS% %GRADLE_OPTS% "-Dorg.gradle.appname=%APP_BASE_NAME%" -classpath "%CLASSPATH%" org.gradle.wrapper.GradleWrapperMain %*

:end
@rem End local scope for the variables with windows NT shell
if %ERRORLEVEL% equ 0 goto mainEnd

:fail
set EXIT_CODE=%ERRORLEVEL%
if %EXIT_CODE% equ 0 set EXIT_CODE=1
if not ""=="%GRADLE_EXIT_CONSOLE%" exit %EXIT_CODE%
exit /b %EXIT_CODE%

:mainEnd
if "%OS%"=="Windows_NT" endlocal

:omega
'@
Set-Content -Path "gradlew.bat" -Value $gradlewBat -NoNewline
Write-Host "  ✓ Created gradlew.bat" -ForegroundColor Green

# Create gradlew (Unix script - for completeness)
Write-Host "Creating gradlew (Unix)..." -ForegroundColor Yellow
$gradlew = @"
#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as ksh or
#       bash, then to run this script, type that shell name before the whole
#       command line, like:
#
#           ksh Gradle
#
#       Busybox and similar reduced shells will NOT work, because this script
#       requires all of these POSIX shell features:
#         * functions;
#         * expansions \`$var\`, \`\${var}\`, \`\${var:-default}\`, \`\${var+SET}\`,
#           \`\${var#prefix}\`, \`\${var%suffix}\`, and \`\$( cmd )\`;
#         * compound commands having a testable exit status, especially \`case\`;
#         * various built-in commands including \`command\`, \`set\`, and \`ulimit\`.
#
#   Important for patching:
#
#   (2) This script targets any POSIX shell, so it avoids extensions provided
#       by Bash, Ksh, etc; in particular arrays are avoided.
#
#       The "traditional" practice of packing multiple parameters into a
#       space-separated string is a well documented source of bugs and security
#       problems, so this is (mostly) avoided, by progressively accumulating
#       options in "\$@", and eventually passing that to Java.
#
#       Where the inherited environment variables (DEFAULT_JVM_OPTS, JAVA_OPTS,
#       and GRADLE_OPTS) rely on word-splitting, this is performed explicitly;
#       see the in-line comments for details.
#
#       There are tweaks for specific operating systems such as AIX, CygWin,
#       Darwin, MinGW, and NonStop.
#
#   (3) This script is generated from the Groovy template
#       https://github.com/gradle/gradle/blob/HEAD/platforms/core-configuration/scripts/src/main/resources/org/gradle/api/internal/plugins/unixStartScript.txt
#       within the Gradle project.
#
#       You can find Gradle at https://github.com/gradle/gradle/.
#
##############################################################################

# Attempt to set APP_HOME

# Resolve links: \$0 may be a link
app_path=\$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=\$( cd "\${APP_HOME:-./}" && pwd -P )/ && [ -d "\$APP_HOME" ] && [ ! -L "\$APP_HOME" ]
do
    APP_HOME=\${APP_HOME%/*}
done
APP_HOME=\$( cd "\${APP_HOME:-./}" && pwd -P )

APP_NAME="Gradle"
APP_BASE_NAME=\${0##*/}

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
    echo "\$*"
} >&2

die () {
    echo
    echo "\$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "\$( uname )" in
  CYGWIN* )
    cygwin=true
    ;;
  Darwin* )
    darwin=true
    ;;
  MSYS* | MINGW* )
    msys=true
    ;;
  NONSTOP* )
    nonstop=true
    ;;
esac

CLASSPATH=\$APP_HOME/gradle/wrapper/gradle-wrapper.jar


# Determine the Java command to use to start the JVM.
if [ -n "\$JAVA_HOME" ] ; then
    if [ -x "\$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD=\$JAVA_HOME/jre/sh/java
    else
        JAVACMD=\$JAVA_HOME/bin/java
    fi
    if [ ! -x "\$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: \$JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
fi

# Increase the maximum file descriptors if we can.
if ! "\$cygwin" && ! "\$darwin" && ! "\$nonstop" ; then
    case \$MAX_FD in #(
      max*)
        MAX_FD=\$( ulimit -H -n ) ||
            warn "Could not query maximum file descriptor limit"
    esac
    case \$MAX_FD in  #(
      '' | soft) :;; #(
      *)
        ulimit -n \$MAX_FD ||
            warn "Could not set maximum file descriptor limit to \$MAX_FD"
    esac
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * -classpath
#   * -D...appname settings
#   * --module-path (only if needed)
#   * DEFAULT_JVM_OPTS, JAVA_OPTS, and GRADLE_OPTS environment variables.

# For Cygwin or MSYS, switch paths to Windows format before running java
if "\$cygwin" || "\$msys" ; then
    APP_HOME=\$( cygpath --path --mixed "\$APP_HOME" )
    CLASSPATH=\$( cygpath --path --mixed "\$CLASSPATH" )

    JAVACMD=\$( cygpath --unix "\$JAVACMD" )

    # Now convert the arguments - kludge to limit ourselves to /bin/sh
    for arg do
        if
            case \$arg in                                #(
              -*)   false ;;                            # don't mess with options #(
              /?*)  t=\$( cygpath --path --ignore --mixed "\$arg" ) && arg=\$t ;; #(
              *)    false ;;
            esac
        then
            arg=\$( cygpath --path --ignore --mixed "\$arg" )
        fi
        # Roll the args list around exactly as many times as the number of
        # args, so each arg winds up back in the position where it started, but
        # possibly modified.
        #
        # NB: a \`for\` loop captures its iteration list before it begins, so
        # changing the positional parameters here affects neither the number of
        # iterations, nor the values presented in \`arg\`.
        shift                   # remove old arg
        set -- "\$@" "\$arg"      # push replacement arg
    done
fi

# Collect all arguments for the java command;
#   * \${DEFAULT_JVM_OPTS}, \${JAVA_OPTS}, \${GRADLE_OPTS} can contain fragments of
#     shell script including quotes and variable substitutions, so put them in
#     double quotes to make sure that they get re-expanded; and
#   * put everything else in single quotes, so that it's not re-expanded.

set -- \\
        "\${DEFAULT_JVM_OPTS[@]}" \\
        \${JAVA_OPTS:-} \\
        \${GRADLE_OPTS:-} \\
        "\$@" \\
        -classpath "\$CLASSPATH" \\
        org.gradle.wrapper.GradleWrapperMain \\
        "\$@"

# Stop when "xargs" is not available.
if ! command -v xargs >/dev/null 2>&1
then
    die "xargs is not available"
fi

# Use "xargs" to parse quoted args.
#
# With -n1 it outputs one arg per line, with the quotes and backslashes removed.
#
# In Bash we could simply go:
#
#   readarray ARGS < <( xargs -n1 <<<"\$var" ) &&
#   set -- "\${ARGS[@]}" "\$@"
#
# but POSIX shell has neither arrays nor command substitution, so instead we
# post-process each arg (as a line of input to sed) to backslash-escape any
# character that might be a shell metacharacter, then use eval to reverse
# that process (while maintaining the separation between arguments), and wrap
# the whole thing up as a single "set" statement.
#
# This will of course break if any of these variables contains a newline or
# an unmatched quote.
#

eval "set -- \$(
        printf '%s\n' "\$DEFAULT_JVM_OPTS \$JAVA_OPTS \$GRADLE_OPTS" |
        xargs -n1 |
        sed ' s~[^-[:alnum:]+,./:=@_]~\\&~g; ' |
        tr '\n' ' '
    )" '"\$@"'

exec "\$JAVACMD" "\$@"
"@
Set-Content -Path "gradlew" -Value $gradlew
Write-Host "  ✓ Created gradlew" -ForegroundColor Green

Write-Host "`n=== Gradle Wrapper Setup Complete! ===" -ForegroundColor Green
Write-Host "`nYou can now run:" -ForegroundColor Yellow
Write-Host "  .\gradlew.bat setupDecompWorkspace" -ForegroundColor White
Write-Host "  .\gradlew.bat build" -ForegroundColor White
